### ISSUE TITLE
Unexpected behavior - OrderedDict should be treated like a dict by serialize_variable

### ISSUE THREAD

**Issue by damm89** [maykinmedia/django-camunda#7]
**Describe the bug**
Calling serialize_variable with a collections.OrderedDict breaks.

**To Reproduce**
1. Create an ordereddict.
2. Load it in serialize_variable

**Expected behavior**
Similar treatment to dict (e.g., json.dumps can be called)

**Comment by sergei-maertens** [comment]
Just merged the PR, we've got another change lined up so a new version will be released in the course of the day.
